# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: main.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmain.proto\"(\n\x08\x45lements\x12\r\n\x05\x65lmt1\x18\x01 \x01(\x05\x12\r\n\x05\x65lmt2\x18\x02 \x01(\x05\"\x18\n\x06Result\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x33\n\x0cgRPCExercise\x12#\n\x0b\x61\x64\x64\x32Numbers\x12\t.Elements\x1a\x07.Result\"\x00\x62\x06proto3')



_ELEMENTS = DESCRIPTOR.message_types_by_name['Elements']
_RESULT = DESCRIPTOR.message_types_by_name['Result']
Elements = _reflection.GeneratedProtocolMessageType('Elements', (_message.Message,), {
  'DESCRIPTOR' : _ELEMENTS,
  '__module__' : 'main_pb2'
  # @@protoc_insertion_point(class_scope:Elements)
  })
_sym_db.RegisterMessage(Elements)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'main_pb2'
  # @@protoc_insertion_point(class_scope:Result)
  })
_sym_db.RegisterMessage(Result)

_GRPCEXERCISE = DESCRIPTOR.services_by_name['gRPCExercise']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ELEMENTS._serialized_start=14
  _ELEMENTS._serialized_end=54
  _RESULT._serialized_start=56
  _RESULT._serialized_end=80
  _GRPCEXERCISE._serialized_start=82
  _GRPCEXERCISE._serialized_end=133
# @@protoc_insertion_point(module_scope)
